---
- name: install dovecot
  yum: name={{ item }} state=present
  notify: restart dovecot
  with_items:
    - dovecot
    - dovecot-mysql
    - dovecot-pigeonhole

- name: install packages required to build dovecot-antispam
  yum: name={{ item }} state=installed
  with_items:
    - automake
    - dovecot-devel
    - gcc
    - mercurial
    - openssl-devel

- name: download dovecot-antispam
  hg: repo=http://hg.dovecot.org/dovecot-antispam-plugin
      dest=/root/dovecot-antispam
  notify:
    - build dovecot-antispam

- name: add user `dovecot' to mail group
  user: name=dovecot groups=mail append=true

- name: Ensure /var/s3mtp/mail exists
  file: path=/var/s3mtp/mail
        state=directory
        owner=dovecot
        group=dovecot
        mode=0700

- name: create user maildirs
  file: path=/var/s3mtp/{{ item.domain }}/{{ item.user }}
        state=directory
        owner=dovecot
        group=dovecot
        mode=0700
  with_items: s3mtp_accounts

- name: copy base filter for users
  copy: dest=/var/s3mtp/{{ item.domain }}/{{ item.user }}/.dovecot.sieve
        src=user.dovecot.sieve
        force=no
  with_items: s3mtp_accounts

- name: Config files
  template: src={{ item }}
            dest=/etc/dovecot/{{ item }}
            mode=0600
            owner=dovecot
            group=dovecot
  with_items:
    - local.conf
    - dovecot-sql.conf.ext
    - conf.d/auth-sql.conf.ext
    - conf.d/10-auth.conf
    - conf.d/10-mail.conf
    - conf.d/10-master.conf
    - conf.d/10-ssl.conf
    - conf.d/20-imap.conf
    - conf.d/20-lmtp.conf
  notify:
    - restart dovecot

- name: generate self-signed certificate
  command: openssl req -new -x509 -days 1000 -nodes
           -out "/etc/pki/dovecot/certs/dovecot.pem"
           -keyout "/etc/pki/dovecot/private/dovecot.pem"
           creates=/etc/pki/dovecot/certs/dovecot.pem
  notify:
    - restart dovecot

- name: ensure dovecot enabled and running
  service: name=dovecot state=started enabled=yes

- name: open firewall ports for dovecot
  firewalld: service={{ item }} permanent=true state=enabled
  with_items:
    - imaps
    - pop3s
  notify:
    - reload firewall
