---
- name: restart postfix
  service: name=postfix state=restarted

- name: import postfix sql
  mysql_db: name={{ postfix_db_name }}
            state=import
            target=/root/postfix.sql
            login_user=root
            login_password={{ lookup('password', '../../mysql/files/credentials/root chars=hexdigits') }}

- name: import postfix mail accounts
  mysql_db: name={{ postfix_db_name }}
            state=import
            target=/root/mail_accounts.sql
            login_user=root
            login_password={{ lookup('password', '../../mysql/files/credentials/root chars=hexdigits') }}

