---
- name: copy postfix base sql
  copy: src=postfix.sql dest=/root/postfix.sql

- name: create postfix database
  mysql_db: name={{ postfix_db_name }}
            state=present
            login_user=root
            login_password={{ lookup('password', '../../mysql/files/credentials/root chars=hexdigits') }}
  notify:
    - import postfix sql

- name: create mail accounts sql
  template: src=mail_accounts.sql
            dest=/root/mail_accounts.sql
            owner=root
            group=root
            mode=0600
  tags:
    - accounts
  notify:
    - import postfix mail accounts

- name: create postfix sql user
  mysql_user: name={{ postfix_db_user }}
              host=localhost
              password={{ lookup('password', '../../mysql/files/credentials/' + postfix_db_user + ' chars=hexdigits') }}
              priv={{ postfix_db_name }}.*:ALL
              state=present
              login_user=root
              login_password={{ lookup('password', '../../mysql/files/credentials/root chars=hexdigits') }}

- name: ensure postfix installed
  yum: name=postfix state=installed
  with_items:
    - postfix
    - postgrey
  notify:
    - restart postfix

- name: configure postfix
  template: dest=/etc/postfix/{{ item }} src={{ item }} mode=0644 owner=root
  with_items:
    - dspam_filter_access
    - master.cf
    - main.cf
    - mysql-virtual-mailbox-domains.cf
    - mysql-virtual-mailbox-maps.cf
    - mysql-virtual-alias-maps.cf
  notify:
    - restart postfix

- name: start postfix
  service: name=postfix state=running enabled=yes

- name: open firewall ports for postfix
  firewalld: service=smtp permanent=true state=enabled
  notify:
    - reload firewall
