---
- name: ensure ntp is installed
  yum: pkg=ntp state=installed
  tags: ntp

- name: ensure ntpd is running and enabled
  service: name=ntpd state=running enabled=yes
  tags: ntp

- name: disable selinux
  selinux: state=disabled
  notify:
    - set selinux permissive

- name: set hostname
  hostname: name={{ s3mtp_hostname }}.{{ s3mtp_domain }}
