---
- name: required packages
  yum: name={{ item }} state=present
  with_items:
    - bzip2
    - fuse
    - fuse-devel
    - gcc
    - libattr-devel
    - psmisc
    - python3
    - python3-pip
    - python3-devel
    - python3-apsw
    - rsync
    - sqlite
    - sqlite-devel
    - tar

- name: required python eggs
  pip: name={{ item }} executable=pip-python3 state=present
  with_items:
    - pycrypto
    - llfuse

- name: create /opt/s3mtp
  file: path=/opt/s3mtp/{{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - bin
    - etc
    - etc/s3ql
    - etc/systemd
    - etc/
    - src
    - var

- name: get s3ql source
  get_url: dest=/opt/s3mtp/src/s3ql.tar.bz2 url=https://s3ql.googlecode.com/files/s3ql-2.6.0.tar.bz2

- name: extract s3ql source
  shell: tar -xjf s3ql.tar.bz2 chdir=/opt/s3mtp/src creates=s3ql-2.6

- name: make s3ql build dirs writable
  file: path=/opt/s3mtp/src/s3ql-2.6/build state=directory mode=0777 recurse=yes

- name: compile s3ql
  command: python3 setup.py build_ext --inplace chdir=/opt/s3mtp/src/s3ql-2.6 creates=src/s3ql/deltadump.cpython-33m.so

- name: install s3ql
  command: python3 setup.py install chdir=/opt/s3mtp/src/s3ql-2.6 creates=/usr/bin/s3qlctrl

- name: ensure s3ql mountpoint exists
  file: path=/var/s3mtp state=directory mode=755 owner=root group=root

- name: define s3mtp.authinfo
  template: src=s3mtp.authinfo.j2 dest=/opt/s3mtp/etc/s3ql/s3mtp.authinfo mode=0600 owner=root group=root
  notify:
    - restart s3mtp

- name: define s3mtp.service
  copy: src=s3mtp.service dest=/opt/s3mtp/etc/systemd/s3mtp.service mode=0600
  notify:
    - restart s3mtp

- name: link in s3mtp.service
  file: src=/opt/s3mtp/etc/systemd/s3mtp.service dest=/usr/lib/systemd/system/s3mtp.service state=link
  notify:
    - restart s3mtp

- name: define s3mtp bin/*
  template: src={{ item }}.j2 dest=/opt/s3mtp/bin/{{ item }} mode=0700
  with_items:
    - s3mtp_start.sh
    - s3mtp_stop.sh

- name: ensure s3mtp filesystem mounted - you have to do this bit manually
  service: name=s3mtp state=started enabled=yes
